name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Clone naming-server repo
      - name: Clone naming-server repo
        run: git clone https://github.com/Yakoti/naming-server.git

      - name: Make mvnw executable in naming-server
        run: chmod +x naming-server/mvnw

      - name: Build naming-server
        run: |
          cd naming-server
          ./mvnw clean install

      - name: Start naming-server in background
        run: |
          cd naming-server
          ./mvnw spring-boot:run &
          echo $! > ../naming-server.pid

      - name: Wait for naming-server to be ready
        run: |
          until curl -s http://localhost:8761/actuator/health > /dev/null; do
            echo "Waiting for naming-server to start..."
            sleep 5
          done

      # Make mvnw executable in chat-service (repo root)
      - name: Make mvnw executable
        run: chmod +x mvnw

      # Run integration tests for chat-service
      - name: Run integration tests
        run: ./mvnw verify

      # ✅ Always generate report (even if tests failed)
      - name: Generate Surefire HTML report
        if: always()
        run: ./mvnw surefire-report:report-only -DskipTests

      - name: List generated reports
        if: always()
        run: ls -l target/site/ || echo "No site folder found"

      - name: Zip test reports
        if: always()
        run: |
          mkdir -p test-reports
          if [ -d target/site ]; then
            cp -r target/site/* test-reports/
          fi
          zip -r test-reports.zip test-reports || echo "No reports to zip"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chat-service-test-reports
          path: test-reports.zip

      - name: Stop naming-server
        if: always()
        run: |
          if [ -f naming-server.pid ]; then
            kill $(cat naming-server.pid) || echo "Failed to kill naming-server process"
          else
            echo "naming-server.pid not found, skipping kill"
          fi
